---
- name: Install logstash
  apt:
    name: logstash
    state: present
  when: "inventory_hostname in groups['logstash']"

- name: Configure logstash nodes
  template:
    src: logstash-syslog.conf.j2
    dest: /etc/logstash/conf.d/logstash-syslog.conf
    group: logstash
    mode: 0644
  register: logstash_config
  when: "inventory_hostname in groups['logstash']"

- name: Make sure logstash is started
  systemd: name=logstash state=started enabled=yes
  when:
    - logstash_start_service
    - "inventory_hostname in groups['logstash']"

# To mitigate dropped packets, make sure to increase the Linux kernel receive buffer limit:
- name: SetLinux kernel receive buffer limit
  sysctl:
    name: net.core.rmem_max
    value: 16777216
    sysctl_file: /etc/sysctl.conf
    reload: yes
  when: "inventory_hostname in groups['logstash']"

- name: Restart logstash if config changed
  debug: msg="Restart Logstash due to config changes"
  when: logstash_config.changed
  notify: restart logstash

- meta: flush_handlers

