---
- name: Install kibana
  apt:
    name: kibana
    state: present
  when: "inventory_hostname in groups['kibana']"

- name: Configure kibana nodes
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    group: kibana
    mode: 0644
  when: "inventory_hostname in groups['kibana']"

- name: Make sure kibana is started
  systemd: name=kibana state=started enabled=yes
  when:
    - kibana_start_service
    - "inventory_hostname in groups['kibana']"
