---
- name: JDK | Add Oracle java repo
  apt_repository:
    repo: 'ppa:webupd8team/java'
    state: present
    filename: 'oracle-java'
  tags:
    - jdk

- name: JDK | Set license as accepted
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags:
    - jdk

- name: JDK | Install oracle-java8-installer
  apt:
    name: oracle-java8-installer
    update_cache: yes
    state: present
  tags:
    - jdk
